[CodeTable]
UniqueName=wubixsj
Name=Wubixsj
Name[de]=Wubixsj
Name[ja]=Wubixsj
Name[zh_CN]=五笔字型新世纪
Name[zh_TW]=五筆字型新世纪
Name[ko]=Wubixsj
IconName=wubi
File=wbxsj.mb
AdjustOrder=AdjustNo
Priority=10
UsePY=True
PYKey=z
AutoSend=-1
NoneMatchAutoSend=0
UseMatchingKey=True
MatchingKey=z
AutoPhrase=True
AutoPhraseLength=4
AutoPhrasePhrase=True
SaveAutoPhrase=3
ExactMatch=False
PromptTableCode=False
Symbol=zzzz
Enabled=True
LangCode=zh_CN
NoMatchDontCommit=True
SimpleCodeOrderLevel=2
