[InputMethod]
Name[zh_CN]=wubi
Name=新世纪五笔
Icon=fcitx-wubi06
Label=新世纪
LangCode=zh_CN
Addon=table
Configurable=True

[Table]
File=table/wubi06.main.dict
PageSize=5
CommitAfterSelect=True
CommitWhenDeactivate=False
CommitInvalidSegment=False
UseFullWidth=False
IgnorePunc=False
FirstCandidateAsPreedit=False
QuickPhraseKey=
QuickPhraseText=ABCDEFGHIJLKLMNOPQRSTUVWXYZ
NoSortInputLength=2
OrderPolicy=No
UseSystemLanguageModel=False
UseContextRelatedOrder=False
MatchingKey=
PinyinKey=z
AutoSelect=True
AutoSelectLength=-1
AutoSelectRegex=
NoMatchAutoSelectLength=-1
NoMatchAutoSelectRegex=
AutoPhraseLength=0
SaveAutoPhraseAfter=-8
ExactMatch=False
Learning=False
Hint=False
DisplayCustomHint=False
HintSeparator=
CandidateLayoutHint=Horizontal

[Table/PrevPage]
0=Up
1=minus

[Table/NextPage]
0=Down
1=equal
